---
- scm:
    name: git-jenkins-jobs
    scm:
      - git:
          url: git@test.mail.ru/test.git
          credentials-id: jenkins
          branches:
            - FETCH_HEAD
          refspec:  ${{REFSPEC}}