---
- scm:
    name: uploader_scm
    scm:
      - git:
          url: https://github.com/Annazak24/HomeWork8
          credentials-id: jenkins
          branches:
            - FETCH_HEAD
          refspec:  ${{REFSPEC}}