---
- scm:
    name: uploader_scm
    scm:
      - git:
          url: https://github.ru/saint88/uploader
          credentials-id: jenkins
          branches:
            - FETCH_HEAD
          refspec:  ${{REFSPEC}}