FROM centos:centos8.4.2105

RUN mkdir -p /root/jenkins-deployer/config/jobs/jenkins-job-builder

WORKDIR /root/jenkins-deployer/config/jobs/jenkins-job-builder
COPY . /root/jenkins-deployer/config/jobs/jenkins-job-builder

RUN yum update -y && \
    yum install -y python3 python3-pip && \
    pip3 install jinja2 'jenkins-job-builder>=3.11.0'

CMD ["bash"]