- view:
    name: QA
    view-type: list
    description: "QA"
    filter-executors: true
    filter-queue: true
    job-name:
      - jobs_uploader
      - ui_tests
      - api_tests
      - mobile_tests
      - runner_job
    columns:
      - status
      - job
      - build-button
      - weather