
- name: Stop and remove old containers
  shell: docker compose -f /root/selenoid/docker-compose.yaml down --remove-orphans
  ignore_errors: true

- name: Run docker compose file
  shell: docker compose -f /root/selenoid/docker-compose.yaml up -d

- name: Check containers state
  shell: docker compose -f /root/selenoid/docker-compose.yaml ps
  register: docker_output

- name: Show running containers
  debug:
    var: docker_output.stdout_lines