- job-template:
    name: 'ui_tests'
    description: "<h3 style='color: red;'>ui tests runner</h3>"
    project-type: pipeline
    concurrent: true
    node: maven

    parameters:
      - string:
          name: REFSPEC
          description: ""
          default: main

      - text:
          name: CONFIG
          default: |
            browser: chrome
            base_url: https://mail.ru
            remote: false

    pipeline-scm:
      scm:
        - ui_tests_scm
      script-path: jobs/ui_tests.groovy