- job-template:
    name: ui_tests
    project-type: pipeline
    description: "UI tests runner"
    concurrent: true

    parameters:
      - choice:
          name: BROWSER
          description: "Choose browser for tests"
          choices:
            - chrome
            - firefox

      - text:
          name: CONFIG
          default: |
            browser: chrome
            base_url: https://example.com
            remote: true
          description: "Test configuration"

    pipeline-scm:
      scm:
        - git:
            url: https://github.com/Annazak24/HomeWork6.git
            branches:
              - main
      script-path: Jenkinsfile