- job:
    name: jobs_uploader
    project-type: pipeline
    description: "Jobs uploader"
    parameters:
      - string:
          name: REFSPEC
          default: main
          description: "Branch"
    pipeline-scm:
      scm:
        - uploader_scm
      script-path: config/jobs/jobs_uploader.groovy