---
- name: Deploy Selenoid infrastructure
  hosts: local
  become: true
  gather_facts: true

  roles:
    - playbook-selenoid/roles/docker
    - playbook-selenoid/roles/rendering_configs
    - playbook-selenoid/roles/docker-compose